# Generated by Django 5.2.7 on 2025-11-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='qr_image',
        ),
        migrations.AddField(
            model_name='ticket',
            name='qr_code_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
