# Generated by Django 5.2.7 on 2025-11-03 00:25

import uuid
from django.db import migrations, models


def generate_unique_tokens(apps, schema_editor):
    """Assign a unique token to all existing tickets."""
    Ticket = apps.get_model("tickets", "Ticket")
    for ticket in Ticket.objects.all():
        ticket.token = str(uuid.uuid4())
        ticket.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        # 1️⃣ Step 1: Add token field temporarily (nullable)
        migrations.AddField(
            model_name='ticket',
            name='token',
            field=models.CharField(
                max_length=100,
                unique=False,        # temporarily not unique
                null=True,
                editable=False,
                default=None
            ),
        ),

        # 2️⃣ Step 2: Fill existing records with unique tokens
        migrations.RunPython(generate_unique_tokens),

        # 3️⃣ Step 3: Enforce uniqueness and default for new records
        migrations.AlterField(
            model_name='ticket',
            name='token',
            field=models.CharField(
                max_length=100,
                unique=True,
                editable=False,
                default=uuid.uuid4
            ),
        ),

        # 4️⃣ Step 4: Update status field choices
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(
                max_length=20,
                default='active',
                choices=[
                    ('active', 'Active'),
                    ('used', 'Used'),
                    ('expired', 'Expired'),
                    ('invalid', 'Invalid')
                ],
            ),
        ),
    ]
